spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bank_loan_db
    
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka