ALTER TABLE IF EXISTS compte DROP CONSTRAINT IF EXISTS compte_statut_check;
ALTER TABLE IF EXISTS compte ADD CONSTRAINT compte_statut_check
CHECK (statut IN ('EN_ATTENTE_ACTIVATION', 'ACTIF', 'REJETE', 'SUSPENDU', 'CLOTURE'));
